// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_WebSite_DashBoardApi.Models.Context;

namespace SD_WebSite_DashBoardApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210706160445_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Administrador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.ToTable("adminstrador");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Componente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomeComponente")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_componente");

                    b.Property<long?>("PaginaId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PaginaId");

                    b.ToTable("componente");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Pagina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomePagina")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_pagina");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.ToTable("pagina");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Componente", b =>
                {
                    b.HasOne("SD_WebSite_DashBoardApi.Models.Pagina", null)
                        .WithMany("Componente")
                        .HasForeignKey("PaginaId");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Pagina", b =>
                {
                    b.Navigation("Componente");
                });
#pragma warning restore 612, 618
        }
    }
}
