// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SD_WebSite_DashBoardApi.Models.Context;

namespace SD_WebSite_DashBoardApi.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20210708154726_addFkComponenteRebase")]
    partial class addFkComponenteRebase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("ComponentePagina", b =>
                {
                    b.Property<long>("ComponenteId")
                        .HasColumnType("bigint");

                    b.Property<long>("PaginaIdId")
                        .HasColumnType("bigint");

                    b.HasKey("ComponenteId", "PaginaIdId");

                    b.HasIndex("PaginaIdId");

                    b.ToTable("ComponentePagina");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Administrador", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long?>("ComponenteId")
                        .HasColumnType("bigint");

                    b.Property<string>("Password")
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Usuario")
                        .HasColumnType("longtext")
                        .HasColumnName("usuario");

                    b.HasKey("Id");

                    b.HasIndex("ComponenteId");

                    b.ToTable("adminstrador");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Componente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomeComponente")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_componente");

                    b.HasKey("Id");

                    b.ToTable("componente");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Pagina", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("NomePagina")
                        .HasColumnType("longtext")
                        .HasColumnName("nome_pagina");

                    b.Property<int>("Ordem")
                        .HasColumnType("int")
                        .HasColumnName("ordem");

                    b.HasKey("Id");

                    b.ToTable("pagina");
                });

            modelBuilder.Entity("ComponentePagina", b =>
                {
                    b.HasOne("SD_WebSite_DashBoardApi.Models.Componente", null)
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SD_WebSite_DashBoardApi.Models.Pagina", null)
                        .WithMany()
                        .HasForeignKey("PaginaIdId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Administrador", b =>
                {
                    b.HasOne("SD_WebSite_DashBoardApi.Models.Componente", null)
                        .WithMany("AdministradorId")
                        .HasForeignKey("ComponenteId");
                });

            modelBuilder.Entity("SD_WebSite_DashBoardApi.Models.Componente", b =>
                {
                    b.Navigation("AdministradorId");
                });
#pragma warning restore 612, 618
        }
    }
}
